# Generated by Django 4.1.7 on 2023-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='uploads/profile_pictures/default.png', upload_to='uploads/item_pictures'),
        ),
    ]
