# Generated by Django 4.1.7 on 2023-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripePage', '0004_alter_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='uploads/item_pictures/default.jpg', upload_to='uploads/item_pictures'),
        ),
    ]
